name: CI

on:
  push:
    branches:
      - main
      - 1.0.0
  pull_request:
    branches:
      - main
      - 1.0.0

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run style check
        uses: ./.github/actions/style
        with:
          path: .

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Upload Doxygen documentation
        uses: actions/upload-artifact@v4
        with:
          name: Doxygen Documentation
          path: docs/html

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build project
        run: |
          platformio run
